readium/r2-navigator-swift

Cartfile.resolved
r2-navigator-swift/NavigatorViewController.swift
r2-navigator-swift/TriptychView.swift
r2-navigator-swift/WebView.swift

- func didChangedDocumentPage(currentDocumentIndex: Int)    
- func didChangedPaginatedDocumentPage(currentPage: Int, documentTotalPage: Int)

Added two delegate methods about pagination in document

---

r2-navigator-swift/WebView.swift

This will dismiss text selection on webview when tapping somewhere else.

Dismiss text selection

---

r2-navigator-swift/BinaryLocation.swift
r2-navigator-swift/CbzNavigatorViewController.swift
r2-navigator-swift/Disjunction.swift
r2-navigator-swift/NavigatorViewController.swift
r2-navigator-swift/TriptychView.swift
r2-navigator-swift/UserSettings.swift
r2-navigator-swift/WebView.swift
r2-navigator-swift/r2-navigator-swift.h

Fix readium/r2-testapp-swift#134

Add copyright headers and comments cleanup

---

r2-navigator-swift/UserSettings.swift

Fix readium/r2-testapp-swift#141 - Basic handling of line height in user settings.

Add line height user setting support

---

r2-navigator-swift/NavigatorViewController.swift

This PR expose some value to use for bookmark feature.
The current scroll progression `currentDocumentProgression`
The current document index in visible webview `currentDocumentIndex`
Also add a scroll function to reach the position stored in bookmark.

Add some helper functions for bookmark

---

r2-navigator-swift/WebView.swift

This PR adds an activity indicator to the web view. This is to give a better UX when navigating in large documents on slow devices.

Activity indicator in webview

---

r2-navigator-swift/WebView.swift

Fix memory leak in the web view

---

r2-navigator-swift/EPUB/EPUBNavigatorViewController.swift
r2-navigator-swift/EPUB/FixedWebView.swift
r2-navigator-swift/EPUB/ReflowableWebView.swift
r2-navigator-swift/EPUB/Resources/gestures.js
r2-navigator-swift/EPUB/WebView.swift

Fixes #55 
Fixes https://github.com/readium/r2-testapp-swift/issues/239

Fixes RTL taps and scrollToPosition

---

r2-navigator-swift/EPUB/DocumentWebView.swift
r2-navigator-swift/EPUB/ReflowableDocumentWebView.swift

Fixes https://github.com/readium/r2-testapp-swift/issues/109
Fixes https://github.com/readium/r2-testapp-swift/issues/105

Support for VoiceOver

---

r2-navigator-swift.xcodeproj/project.pbxproj
r2-navigator-swift/EPUB/EPUBFixedSpreadView.swift
r2-navigator-swift/EPUB/EPUBNavigatorViewController.swift
r2-navigator-swift/EPUB/EPUBReflowableSpreadView.swift
r2-navigator-swift/EPUB/EPUBSpreadView.swift
r2-navigator-swift/Toolkit/CompletionList.swift
r2-navigator-swift/Toolkit/PaginationView.swift

Various fixes in the EPUB navigator

---

r2-navigator-swift/CBZ/CBZNavigatorViewController.swift
r2-navigator-swift/EPUB/EPUBNavigatorViewController.swift
r2-navigator-swift/EPUB/EPUBSpread.swift
r2-navigator-swift/VisualNavigator.swift

See https://github.com/readium/r2-shared-swift/issues/81

Align the Publication models with Kotlin

---

r2-navigator-swift/EPUB/UserSettings.swift

* Enable publisher's defaults by default
* Increase the default line-height to 1.5

Fix default user settings

---

r2-navigator-swift/EPUB/EPUBNavigatorViewController.swift
r2-navigator-swift/PDF/PDFNavigatorViewController.swift

See https://github.com/readium/r2-shared-swift/pull/90

Use immutable Publication shared models

---

r2-navigator-swift/Toolkit/PaginationView.swift

Fix #107 
The views were always laid out from left to right, so the scrolling offset in RTL was wrong.

Fix EPUB RTL page positioning

---

r2-navigator-swift/EPUB/EPUBNavigatorViewController.swift
r2-navigator-swift/EditingAction.swift
r2-navigator-swift/PDF/PDFNavigatorViewController.swift

Implement the [Streamer API](https://github.com/readium/architecture/pull/139) and [Content Protection](https://github.com/readium/architecture/pull/140) proposals

Implement Streamer API and Content Protection

---

CHANGELOG.md
r2-navigator-swift/EPUB/EPUBFixedSpreadView.swift
r2-navigator-swift/EPUB/EPUBNavigatorViewController.swift
r2-navigator-swift/EPUB/EPUBReflowableSpreadView.swift
r2-navigator-swift/EPUB/EPUBSpread.swift
r2-navigator-swift/EPUB/EPUBSpreadView.swift
r2-navigator-swift/Toolkit/CompletionList.swift
r2-navigator-swift/Toolkit/PaginationView.swift

EPUB resources are now preloaded serially instead of all in one go. This reduces the render time of the current resource a lot as well as memory usage.

Optimize performances of preloaded EPUB resources

---

CHANGELOG.md
r2-navigator-swift/EPUB/EPUBNavigatorViewController.swift
r2-navigator-swift/EPUB/EPUBSpreadView.swift

Allows client integrations to access the internal WKWebView in order to add custom user scripts, etc. Added as an extension rather than modifying the existing structure.

Added extension exposing the spread WKWebView

---

R2Navigator.podspec

Discussion on https://github.com/readium/r2-shared-swift/pull/129

add podspec

---

Cartfile
Cartfile.resolved
README.md
r2-navigator-swift.xcodeproj/project.pbxproj

See https://github.com/readium/r2-testapp-swift/issues/351#issuecomment-829250100

Fix build on Xcode 12.5

---

r2-navigator-swift/EPUB/EPUBFixedSpreadView.swift

Regression introduced with the SPM support.

Fix loading FXL HTML wrapper
